### ISSUE TITLE
Vagrant and VirtualBox not required to build project

### ISSUE THREAD

**Issue by mslinn** [snowplow/aws-lambda-scala-example-project#6]
The instructions say:

```
 host$ git clone https://github.com/snowplow/aws-lambda-scala-example-project.git
 host$ cd aws-lambda-scala-example-project
 host$ vagrant up && vagrant ssh
guest$ cd /vagrant
guest# sbt assembly
```

This is all that is required to build the project:

```
 host$ git clone https://github.com/snowplow/aws-lambda-scala-example-project.git
 host$ cd aws-lambda-scala-example-project
 host$ sbt assembly
```

The docs do not mention running the project under Vagrant and also don't mention how to work with VirtualBox. I don't know for sure, but I don't think either of them are required in order to launch this process under Ubuntu, for example, or even AWS Lambda. Perhaps a Windows user might find Vagrant helpful to run the program after it is built. It seems that the instructions for Vagrant and VirtualBox just add complexity for no additional benefit.

**Comment by alexanderdean** [comment]
Hi @mslinn - you can see the technologies required to run this project here:

https://github.com/snowplow/aws-lambda-scala-example-project/blob/master/vagrant/up.playbooks

The `vagrant up && vagrant ssh` dance is standard across all Snowplow OSS projects and significantly reduces the amount of manual setup a developer has to do.

**Comment by mslinn** [comment]
Depends what the developer wants to do. If they just want to build and deploy this project without running it locally first, which is what the docs say, then there is no need to do the dance.

**Comment by alexanderdean** [comment]
Well, the section is called "Developer Quickstart", not "Existing Scala Developer Quickstart"
