### ISSUE TITLE
sbt-assembly output does not have .jar filetype

### ISSUE THREAD

**Issue by mslinn** [snowplow/aws-lambda-scala-example-project#7]
Not having the correct filetype is confusing for humans and prevents software tools from working correctly. This is easily fixed by changing the last line of `build.sbt` to:

```
jarName in assembly := { s"${name.value}-${version.value}.jar" }
```

Line 43 of `tasks.py` also needs to reference the new jar file name:

```
JARFILE = "./target/scala-2.11/aws-lambda-scala-example-project-0.1.0.jar"
```

**Comment by alexanderdean** [comment]
Agree, we should change this
