### ISSUE TITLE
No project/build.properties file

### ISSUE THREAD

**Issue by mslinn** [snowplow/aws-lambda-scala-example-project#8]
SBT projects specify all dependencies in `.sbt` files, except the version of SBT to use. That dependency is specified in `project/build.properties`. The following specifies the current version version of SBT and I have tested to see that it works with this project:

```
sbt.version=0.13.9
```

A `project/build.properties` file should be added to the project with the above content so that it will continue to build properly in the future.

**Comment by alexanderdean** [comment]
Yep agree
